# Generated by Django 4.1.7 on 2023-04-02 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibmunapp', '0002_alter_announcements_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField()),
            ],
        ),
    ]
